language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t lkupke/docker-aws -f Dockerfile.dev .

script:
  - docker run lkupke/docker-aws npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-aws"
  env: "DockerAws-env"
  bucket_name: "elasticbeanstalk-us-east-1-160174575790"
  bucket_path: "docker-aws"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"